modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
loggFile="logo.png"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="libx"
    mandatory=true
    versionRange="[1.19.2-4.2.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="botania"
    mandatory=true
    versionRange="[1.19.2-439,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="botanicalmachinery"
    mandatory=true
    versionRange="[1.19.2-2.0.5,)"
    ordering="NONE"
    side="BOTH"