name: Feature request
description: Suggest an idea
labels: [ enhancement ]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe your idea
      placeholder: A clear and reasoned description of your idea. Preferably in great detail
    validations:
      required: true